# It will automatically install dependencies from requirements.txt file 
FROM python:3

# this is what the on-build image expects your code to be
WORKDIR /home

CMD ["python2.7","-m","CGIHTTPServer","80"]