version: '3'

services:
  products-service:
    build: ./products
    volumes:
      - ./products:/usr/src/app
    ports:
      - 5001:80
    depends_on: 
      - database-service
  services-service:
    build: ./services
    volumes:
      - ./services:/usr/src/app
    ports:
      - 5002:80
    depends_on: 
      - database-service

  database-service:
    build: ./database
    volumes:
      - ./database:/home/
    # ports:
    #   - 5002:9090

  frontend-service:
    build: ./frontend
    depends_on: 
      - products-service
      - services-service
    volumes:
      - ./frontend:/home/
    ports:
      - 5003:80